[workspace]
members = [
    "rcc_lexer",
    "rcc_span",
    "rcc_error",
    "rcc_parser",
    "rcc_bytecode",
    "rcc_main",
    "rcc_opt",
    "rcc_backend_asm",
    "rcc_asm_arm",
    "rcc_asm_x86",
]
