[package]
name = "rcc_error"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rcc_span = { version = "0.0.0", path = "../rcc_span" }
termcolor = "1.2.0"
